[GL-3536] solved the errors with lint globbing and updated
g-loot/action-deploy-helm pull request #27
Opened 2022-08-10 08:17 UTC by Warrior0078

1. while the lint was executing it gave an error with prevent spell check with globbing.
2. to solve this i have updated the line which have $symbol with ""

2022-08-12 08:24 UTC, philipgloot requested changes

2022-08-12 08:24 UTC, philipgloot commented on .github/workflows/main.yml
> +        VALIDATE_ALL_CODEBASE: false
Can you run it once withouth `VALIDATE_ALL_CODEBASE: false` to test all files

2022-08-16 15:03 UTC, philipgloot requested changes

2022-08-16 15:03 UTC, philipgloot commented on Dockerfile
> +RUN apk add --no-cache openssl=1.1.1b-r1 && \
`1.1.1b-r1` is not the latest version

2022-08-16 15:03 UTC, philipgloot commented on value-files/override-new-name.yaml
> +name: "github-action-helm-test-multiple-files"
fix indentation

2022-08-16 15:03 UTC, philipgloot commented on value-files/old-name.yaml
> +      port: 80
Fix indentation

2022-08-16 15:03 UTC, philipgloot commented on deploy.sh
>  helm "${helm_command_array[@]}" "${helm_args_array[@]}"
If changing a variable name it needs to be changed everywhere

2022-08-16 15:03 UTC, philipgloot commented on deploy.sh
> +readonly export RELEASE_NAME=$(/applicationName.sh "$INPUT_HELM_ARGS")
Look here how to set readonly variables https://unix.stackexchange.com/questions/66627/is-there-anyway-to-set-a-readonly-environment-variable#:~:text=readonly%20VAR%3Dfoo%20%20%20%23%20POSIX

`readonly VAR=foo`

2022-08-16 15:03 UTC, philipgloot commented on deploy.sh
> +export REPOSITORY="$(eval "REPO=$INPUT_REPOSITORY" && echo $REPO" | sed 's/\//__/') # Replace '/' with '__', since labels don't support '/'
the second " doesnt seem to be placed correct

2022-08-16 15:03 UTC, philipgloot commented on applicationName.sh
> -echo $APPLICATION_NAME
Why is this deleted?

2022-08-16 15:03 UTC, philipgloot commented on applicationName.sh
> -fi
is this suppose to be deleted?

2022-08-16 15:03 UTC, philipgloot commented on applicationName.sh
> +    export readonly APPLICATION_NAME=$(echo "$value" | sed 's/application.name=//g')
Look here how to set readonly variables https://unix.stackexchange.com/questions/66627/is-there-anyway-to-set-a-readonly-environment-variable#:~:text=readonly%20VAR%3Dfoo%20%20%20%23%20POSIX

`readonly VAR=foo
`

2022-08-19 09:15 UTC, Warrior0078 commented
CI deploy has been passed with the new openssl version and checked all the lint errors

2022-08-19 09:20 UTC, philipgloot requested changes

2022-08-19 09:20 UTC, philipgloot commented on value-files/old-name.yaml
> +    port: 80
indentation is wrong

2022-08-19 09:20 UTC, philipgloot commented on value-files/override-new-name.yaml
> +  name: "github-action-helm-test-multiple-files"
indentation is wrong

2022-08-19 09:40 UTC, philipgloot requested changes

2022-08-19 09:40 UTC, philipgloot commented on value-files/override-new-name.yaml
> +    name: "github-action-helm-test-multiple-files"
2 spaces instead of 4

2022-08-19 10:21 UTC, philipgloot requested changes

2022-08-19 10:21 UTC, philipgloot commented on deploy.sh
> +echo "$INPUT_GCP_KEY | base64 -d > /tmp/google_credentials.json"
" " is wrong

2023-07-21 09:19 UTC, esmaeilram commented
we don't use this PR anymore

2023-07-21 09:19 UTC, closed without merging